import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_modal.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_modal.g.dart';

@freezed
abstract class UserModal with _$UserModal {
  const factory UserModal({
    String? token,
    String? error,
  }) = _UserModal;

  factory UserModal.fromJson(Map<String, Object?> json) =>
      _$UserModalFromJson(json);
}
