import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'movie_modal.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'movie_modal.g.dart';

@freezed
abstract class MovieModal with _$MovieModal {
  const factory MovieModal({
    @Default(null) int? total,
    @Default(null) int? page,
    @Default(null) int? pages,
    @Default([]) @JsonKey(name: 'tv_shows') List<TVShows>? tvShows,
  }) = _MovieModal;

  factory MovieModal.fromJson(Map<String, Object?> json) =>
      _$MovieModalFromJson(json);
}

@freezed
abstract class TVShows with _$TVShows {
  const factory TVShows({
    @Default(null) int? id,
    @Default(null) String? name,
    @Default(null) String? permalink,
    @Default(null) @JsonKey(name: 'start_date') String? startDate,
    @Default(null) @JsonKey(name: 'end_date') String? endDate,
    @Default(null) String? country,
    @Default(null) String? network,
    @Default(null) String? status,
    @Default(null)
    @JsonKey(name: 'image_thumbnail_path')
    String? imageThumbnail,
  }) = _TVShows;

  factory TVShows.fromJson(Map<String, Object?> json) =>
      _$TVShowsFromJson(json);
}
